apiVersion: v1
kind: Secret
metadata:
  name: {{ template "imagepullsecret.uname" . }}
  namespace: {{ required "The namespace is required" .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ required "imagePullSecret is required" .Values.imagePullSecret }}