apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "scheduler.uname" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "scheduler.selectorLabels" . | nindent 4}}
  ports:
    - port: {{ .Values.scheduler.port }}
      name: scheduler-svc
      protocol: TCP
      targetPort: scheduler-svc

